### ISSUE TITLE
_this._root.setNativeProps is not a function on react-native-web

### ISSUE THREAD

**Issue by cornejobarraza** [magicismight/react-native-root-toast#172] opened 2023-12-21 23:02 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Some days ago I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-root-toast@3.5.1` for the project I'm working on.

Here is the diff that solved my problem, a simple check to prevent setting native props on the web:

```diff --git a/node_modules/react-native-root-toast/lib/ToastContainer.js b/node_modules/react-native-root-toast/lib/ToastContainer.js
index 6c77e3e..0c88bb0 100644
--- a/node_modules/react-native-root-toast/lib/ToastContainer.js
+++ b/node_modules/react-native-root-toast/lib/ToastContainer.js
@@ -12,7 +12,8 @@ import {
     Easing,
     Keyboard,
     SafeAreaView,
-    TouchableWithoutFeedback
+    TouchableWithoutFeedback,
+    Platform
 } from 'react-native';
 import { ViewPropTypes, TextPropTypes } from 'deprecated-react-native-prop-types';
 const TOAST_MAX_WIDTH = 0.8;
@@ -152,6 +153,7 @@ class ToastContainer extends Component {
         this.keyboardListener?.remove();
     };
 
+    _platform = Platform.OS;
     _animating = false;
     _root = null;
     _hideTimeout = null;
@@ -176,9 +178,13 @@ class ToastContainer extends Component {
         if (!this._animating) {
             clearTimeout(this._hideTimeout);
             this._animating = true;
-            this._root.setNativeProps({
-                pointerEvents: 'auto'
-            });
+            if (this._platform !== 'web') {
+                this._root.setNativeProps({
+                    pointerEvents: 'auto'
+                });
+            } else {
+                this._root.style.pointerEvents = 'auto';
+            }
             this.props.onShow && this.props.onShow(this.props.siblingManager);
             Animated.timing(this.state.opacity, {
                 toValue: this.props.opacity,
@@ -202,9 +208,13 @@ class ToastContainer extends Component {
         clearTimeout(this._hideTimeout);
         if (!this._animating) {
             if (this._root) {
-                this._root.setNativeProps({
-                    pointerEvents: 'none'
-                });
+                if (this._platform !== 'web') {
+                    this._root.setNativeProps({
+                        pointerEvents: 'none'
+                    });
+                } else {
+                    this._root.style.pointerEvents = 'none';
+                }
             }
 
             if (this.props.onHide) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by darvinjsdprog** [comment] 2023-12-27 20:37
Had the same issue and implemented the same solution and it works! 
The issue is only present on the web. @cornejobarraza Thanks!

**Comment by cornejobarraza** [comment] 2023-12-29 07:10
> Had the same issue and implemented the same solution and it works! The issue is only present on the web. @cornejobarraza Thanks!

I'm glad this worked for you, and thanks to your comment I found I left a `setNativeProps` outside of an if statement. If you used this same diff please check it and correct it too 😃

**Comment by cornejobarraza** [comment] 2023-12-29 07:11
> Had the same issue and implemented the same solution and it works! The issue is only present on the web. @cornejobarraza Thanks!

@darvinjsdprog I'm glad this worked for you, and thanks to your comment I found I left a `setNativeProps` outside of an if statement. If you used this same diff please check it and correct it too 😃

**Comment by game-geek** [comment] 2024-02-28 19:41
Yeah, had the same issue too 😬!  
Hope this fix gets merged in the main branch!

**Comment by Ulthran** [comment] 2024-04-25 23:54
Is there any reason not to implement this? Would love to use this across web and mobile.

**Comment by cornejobarraza** [comment] 2024-04-26 00:11
> Is there any reason not to implement this? Would love to use this across web and mobile.

I think the project is no longer maintained as it used to :( multiple open issues

**Comment by sunnylqm** [comment] 2024-04-26 23:53
would like to review and merge if someone can make a pr

**Comment by cornejobarraza** [comment] 2024-04-27 08:11
> would like to review and merge if someone can make a pr

Done, please check PR https://github.com/magicismight/react-native-root-toast/pull/178

**Closed** 2024-04-28 05:06 UTC
